---
title: "Publications"
---

* HM and H. Rieger. Optimal number of agents in a collective search and when to launch them. Phys. Rev. E 111, 064112 (2025) <https://doi.org/10.1103/PhysRevE.111.064112>
* HM, A. Wysocki and H. Rieger. Collective chemotactic search strategies, arXiv:2409.04262 (2024)
* HM and H. Rieger. Non-Markovian and Collective Search Strategies. In: D. Grebenkov, R. Metzler, G. Oshanin (eds), Target Search Problems. Springer, Cham. (2024)
* HM and H. Rieger. Alignment interaction and band formation in assemblies of auto-chemorepulsive walkers. Phys. Rev. E 108(3), 034604 (2023) <https://doi.org/10.1103/PhysRevE.108.034604>
* HM, H. Rieger. Optimal non-markovian search strategies with ։-step memory. Phys. Rev. Lett. 127(7), 070601 (2021)
* HM, F. Glatzel, W. Wöhler, T. Schilling. Evaluation of memory effects at phase transitions and during relaxation processes. Phys. Rev. E 103(2), 022102 (2021)
* HM, S. Wolf, G. Stock, T. Schilling. A numerical procedure to evaluate memory effects in non-equilibrium coarse-grained models. Adv. Theory Sim. 2020, 2000197 (2020)
* HM, P. Pelagejcev, T. Schilling. Non-Markovian out-of-equilibrium dynamics: A general numerical procedure to construct time-dependent memory kernels for coarse-grained observables. Europhysics Letters 128, 40001 (2019)
* A. Kuhnhold, HM, G. Amati, P.Pelagejcev, T. Schilling. Derivation of an exact, nonequilibrium framework for nucleation: Nucleation is a priori neither diffusive nor Markovian. Phys. Rev. E 100(5), 052140 (2019)
* HM, T. Voigtmann and T. Schilling. On the dynamics of reaction coordinates in classical, time-dependent, many-body processes. J. Chem. Phys. 150(17), 174118 (2019)
* G. Amati, HM, T. Schilling. Memory effects in the Fermi-Pasta-Ulam model. J. Stat. Phys. 174(1), 219-257 (2019)
* HM, T. Voigtmann and T. Schilling. On the non-stationary generalized Langevin equation. J. Chem. Phys. 147(21), 214110 (2017)
* M. Dixit, HM and T. Schilling. Connectivity percolation in suspensions of attractive square-well spherocylinders. Phys. Rev. E 93(1), 012116 (2016)
* HM, P. van der Schoot and T. Schilling. Percolation in suspensions of polydisperse hard rods: quasi universality and finite-size effects. J. Chem. Phys. 143(4), 044901 (2015)